### ISSUE TITLE
Gallery dots option is saved as "Keine" or "None" in english. So dots navigation can not be hidden.

### ISSUE THREAD

**Issue by ascheider** [shopware/platform#3641] opened 2024-04-03 13:13 UTC
### PHP Version

8.2

### Shopware Version

6.6.0.2

### Expected behaviour

Hide gallery dot navigation in product layout.

### Actual behaviour

After set the option, the navigation still shown, because of hardcoded language values "Keine" or "None".

### How to reproduce

See PR which describes the problem: https://github.com/shopware/shopware/pull/3639

**Comment by MBDealer** [comment] 2024-05-29 07:31
The same behavior is also present in arrow navigation.

**Comment by mitelg** [comment] 2024-10-21 15:04
Closed as duplicate of https://github.com/shopware/shopware/issues/4499

**Closed as completed by mitelg** 2024-10-21 15:04 UTC
