### ISSUE TITLE
Cart is lost after logging in again

### ISSUE THREAD

**Issue by nyze2oo9** [shopware/platform#3668] opened 2024-04-15 14:35 UTC
### PHP Version

8.3

### Shopware Version

6.5.8.8

### Expected behaviour

1. A customer logs in via `store-api.account.login`
2. The customer add at least one product to the cart `store-api.checkout.cart.add`
3. The customer logs out via `store-api.account.logout`
4. The customer logs in again.

The old cart should be linked to the new context token or the old context token should be linked to the customer again.

### Actual behaviour

1. A customer logs in via `store-api.account.login`
2. The customer add at least one product to the cart `store-api.checkout.cart.add`
3. The customer logs out via `store-api.account.logout`
4. The customer logs in again.

Old context is still in `sales_channel_api_context` 

```json
  {
    "token": "1",
    "payload": "{\"expired\": false, \"customerId\": null}",
    "sales_channel_id": "...",
    "customer_id": null,
    "updated_at": "2024-04-15 13:54:06"
  }
```

A new context exists:
```json
  {
    "token": "2",
    "payload": "{\"expired\": false, \"customerId\": \"018ed64348c27210a98e3dacbe47c4ef\", \"permissions\": [], \"billingAddressId\": null, \"shippingAddressId\": null}",
    "sales_channel_id": "...",
    "customer_id": "018ED64348C27210A98E3DACBE47C4EF",
    "updated_at": "2024-04-15 13:58:36"
  }
```

Old Cart is still there with old context token:
```json
  {
    "token": "1",
     ...
    "customer_id": "018ED64348C27210A98E3DACBE47C4EF",
    ...
  }
```

### How to reproduce

1. A customer logs in via `store-api.account.login`
2. The customer add at least one product to the cart `store-api.checkout.cart.add`
3. The customer logs out via `store-api.account.logout`
4. The customer logs in again.
5. Cart is empty

**Comment by jmatthiesen81** [comment] 2024-04-16 10:32
The issue is already known https://issues.shopware.com/issues/NEXT-35111. @shyim implemented a fix and released a new version of the security plugin fixing this issue (https://store.shopware.com/en/swag136939272659f/shopware-6-security-plugin.html see changelog). The fix will be also included in the next Shopware release.

**Comment by shyim** [comment] 2024-04-16 10:59
fix is merged, https://github.com/shopware/shopware/commit/7dcf5ab7d4e7fed3f20c7cad91d4f803b5019aca
we are waiting for a bugfix that theme compile is not executed when you use subbundles to make a release

**Comment by shyim** [comment] 2024-04-16 14:06
6.5 version has been released

**Closed as completed by shyim** 2024-04-16 14:06 UTC
