### ISSUE TITLE
Dynamische Produktgruppen

### ISSUE THREAD

**Issue by BoBBer446** [shopware/platform#2142] opened 2021-10-18 14:05 UTC
### PHP Version

8

### Shopware Version

v6.4.5.1 Stable Version

### Expected behaviour

I have created Dynamic Product Groups:
Sold greater than or equal to 20
However, no items are displayed

### Actual behaviour

Result is always empty

### How to reproduce

Create a dynamic product group and sort it by selling

![image](https://user-images.githubusercontent.com/10163536/137747367-efad7e95-df31-4ca2-8898-33d761e3eded.png)

**Comment by shyim** [comment] 2023-01-27 14:24
I can't reproduce it as it's very old I will close it. Feel free to reopen

**Closed as completed** 2023-01-27 14:24 UTC
