### ISSUE TITLE
500 Error on /store-api/_info/open-api-schema.json Call to a member function toJson() on null

### ISSUE THREAD

**Issue by BlackScorp** [shopware/platform#2483] opened 2022-05-12 12:14 UTC
### PHP Version

7.4

### Shopware Version

6.4.4.1

### Expected behaviour

See all json schemas for all my entities

### Actual behaviour

500 error page

### How to reproduce

Open the url on local dev environment 

 yourdomain.ddev.local/store-api/_info/open-api-schema.json

in https://github.com/shopware/core/blob/e513de39f346d7fba0c434b2efe793929b73ae0f/Framework/Api/ApiDefinition/Generator/OpenApi/OpenApiDefinitionSchemaBuilder.php#L184

```php
  // In some entities all fields are hidden, but not the id. This creates unwanted schemas. This removes it again
        if (\count($attributes) === 1 && $attributes[0]->property === 'id') {
            return [];
        }
```

if you have the entity acl_user_role then here the empty array is returned. which then leads to the file https://github.com/shopware/core/blob/ed8b40268fd052d38bd848246f2b6a581f21cd4d/Framework/Api/ApiDefinition/Generator/OpenApi3Generator.php#L147. 

here if we have an empty array, $schema is NULL

**Comment by shyim** [comment] 2023-01-27 14:15
I cannot reproduce it anymore. I will close it as it is very old. Feel free to write if that still not working for u

**Closed as not planned by shyim** 2023-01-27 14:15 UTC
