### ISSUE TITLE
Not possible to add new currency

### ISSUE THREAD

**Issue by isaklafleur** [shopware/platform#2547] opened 2022-06-20 19:07 UTC
### PHP Version

latest

### Shopware Version

latest

### Expected behaviour

Be able to add a new currency or you add worlds currencies, https://en.wikipedia.org/wiki/List_of_circulating_currencies

![image](https://user-images.githubusercontent.com/10033653/174664122-07157227-1daa-4b45-9bae-afadfe605965.png)

But the button is not there

![image](https://user-images.githubusercontent.com/10033653/174664225-d8ce8094-7414-43a8-a10b-fd46e0f59662.png)

### Actual behaviour

No button exist to add new currency. We are in trail mode and testing Shopware 6. We plan to install it on our servers.
The currency we need to add is Nigerian Naira. https://en.wikipedia.org/wiki/Nigerian_naira

### How to reproduce

Go to

https://YOURSTORE.shopware.store/admin#/sw/settings/currency/index?limit=25&page=1&sortBy=currency.name&sortDirection=ASC&naturalSorting=true

**Comment by StevendeVries** [comment] 2022-10-11 11:40
Can't reproduce this behavior, possibly a role issue I guess. Since the version isn't clear (latest) I would propose to close this issue.

**Comment by keulinho** [comment] 2022-10-11 12:43
There is a limitation for cloud shops that currently no additional currencies can be added. In the self hosted on prem version no such limitation apply.

**Closed as completed by keulinho** 2022-10-11 12:43 UTC
