### ISSUE TITLE
composer.lock not up to date with composer.json in shopware/recovery

### ISSUE THREAD

**Issue by sylphlv** [shopware/platform#2940] opened 2023-01-19 21:25 UTC
### PHP Version

8

### Shopware Version

v6.4.18.1

### Expected behaviour

I expected composer.lock to be up to date with composer.json in shopware/recovery :D

### Actual behaviour

https://github.com/shopware/recovery/commit/1ec09446a1b1b2b2abdf02dd19a57cb8f0fd5784

### How to reproduce

...

**Comment by shyim** [comment] 2023-01-27 13:48
I will close this as duplicate of https://github.com/shopware/production/issues/168

**Closed as not planned by shyim** 2023-01-27 13:48 UTC
