### ISSUE TITLE
Inherited extension associated with OneToOne of variant products is always null

### ISSUE THREAD

**Issue by sgoetzie** [shopware/platform#2150] opened 2021-10-22 09:25 UTC
### PHP Version

8.0.10

### Shopware Version

v6.4.99 Stable

### Expected behaviour

When creating variant products I expect them to inherit their parents extensions when associated with OneToOne.

### Actual behaviour

The variants extension is always null and has no relation to its parent in the storefront although the parent product and its extensions are always known and referred to in the admin panel

`{{ product.extensions }}` and `{{ parentProduct.extensions }}` of a variant in the admin:

<img width="826" alt="VariantProductExtensionsAdmin" src="https://user-images.githubusercontent.com/86929016/138427337-ad9b5d44-edea-47fe-9333-50ef613a029d.png">

`{{ dump(product) }}` in any storefront template:

<img width="283" alt="VariantProductExtensionsStorefront" src="https://user-images.githubusercontent.com/86929016/138426865-04985ada-913e-445b-89bc-a00b2976dc8f.png">

### How to reproduce

Either create a new plugin that extends a product with a OneToOneAssociation or go ahead and download the plugin I created to reproduce this error:

[Link to the GitHub repository](https://github.com/sgoetzie/Shopware6OneToOneExtensionInheritanceDemo)

- Install and activate the plugin
- Create a product and variants
- Add a date in 'My Date' in the 'OneToOneExtensionInheritance'-card
- Hit save
- Inspect the (variant) product in the admin and storefront. 
  - The dumps have already been made for you in the extra card in the admin and the product card in the storefront. 
  - In case you have demo data please create a product with a name that's easy to search for or it gets quite messy with the dumps on home.

There are also additional images/descriptions and quite a few links to posts of people with the same problem [in the repository](https://github.com/sgoetzie/Shopware6OneToOneExtensionInheritanceDemo).

**Comment by fschmtt** [comment] 2021-10-29 14:05
This seems related to #2015.

Using your plugin (thanks for your efforts in providing a sample!) I could reproduce the described behaviour. Additionally, I also noticed the following:
* After creating a product with a one-to-one associated `myDate` and generating variants afterwards, the column `product.oneToOneExtensionInheritanceDemo` is filled correctly for the parent and the children.
* At this point, `variant.extensions.oneToOneExtensionInheritanceDemo` is `null` in the Storefront dump.
* Overriding the `myDate` association for a variant, updates the `product.oneToOneExtensionInheritanceDemo` column correctly and creates a new entry in `one_to_one_extension_inheritance_demo`. Looking at the dump in the Storefront, it also holds the (uninherited) `variant.extensions.oneToOneExtensionInheritanceDemo`.
* After activating the inheritance and saving the same variant again, the `product.oneToOneExtensionInheritanceDemo` column is not being set back to the variant parent's one. The `one_to_one_extension_inheritance_demo.my_date` column` is set to `null`. Looking at the dump in the Storefront, `variant.extensions.oneToOneExtensionInheritanceDemo` is still overridden with `variant.extensions.oneToOneExtensionInheritanceDemo.myDate` being `null`.

**Comment by sgoetzie** [comment] 2021-10-29 17:29
Thanks for adding the last two points. I mentioned them in my repository but completely forgot to copy them over here.

So everything in the provided example plugin is done properly and the inheritance should already work like that? Knowing that would lift a big question mark above my and many other heads.

Do you have any workaround at hand?

**Comment by fschmtt** [comment] 2021-11-02 14:56
We will further investigate this issue in https://issues.shopware.com/issues/NEXT-18463.

A possible workaround, mentioned In one of the forum threads in your repository's README, seems to be using a one-to-many association.

**Comment by michielkalle** [comment] 2021-12-04 11:09
I am experiencing the exact same problem.

**Comment by fschmtt** [comment] 2021-12-06 09:07
A fix is currently in review and about to be merged, however won't make it into the upcoming December release as the package has already been built.

For clarification, NEXT-18463 has been closed as a duplicate in favour of https://issues.shopware.com/issues/NEXT-18226.

**Comment by keulinho** [comment] 2021-12-06 10:33
Should be fixed with 486d4edc4eb1a489d2996406bcab9624db6255b3

**Closed as completed by keulinho** 2021-12-06 10:33 UTC
