### ISSUE TITLE
Call to a member function getFlag() on null - 500 Internal Server Error - Delete Cover image - Migrated products SW5 -> SW6

### ISSUE THREAD

**Issue by rubberfashion** [shopware/platform#2453] opened 2022-04-27 21:08 UTC
### PHP Version

7.4.28

### Shopware Version

6.4.9.0

### Expected behaviour

Delete COVER image of a product

### Actual behaviour

500 Internal Server Error.
All NON-COVER images will be deleted, but not the COVER image.

### How to reproduce

Shopware 6.4.9.0
Migration products from SW5 -> SW6
Problem only for variants.
I am not sure if you can reproduce the issue. I uploaded my database on Dockware on a fresh Shopware 6.4.9.0 with same issue. An update to 6.4.10 does not solve the issue
some variants are working, some not (no clue if there is any pattern - i can not found any).
The error occure, when you want to delete the COVER image.
You can set the cover_id for the product in the database to NULL. Then it is working one time. After adding another COVER images, and you want to delete it same error.
For new products generated in SW6 no issue.
If you delete the variant and recreate or clone, there is no issue anymore.
Any ideas?

Request: DELETE http://XXX/api/product/d9e07167b0eb42d2a34be89039ccf9d3/media/9331b8d0b1b8472ea8628012cc2e1be7

Response: {
  "errors": [
    {
      "code": "0",
      "status": "500",
      "title": "Internal Server Error",
      "detail": "Call to a member function getFlag() on null",
      "meta": {
        "trace": [
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/shopware\\/core\\/Framework\\/DataAbstractionLayer\\/Write\\/EntityWriter.php",
            "line": 397,
            "function": "addSetNullOnDeletesCommands",
            "class": "Shopware\\Core\\Framework\\DataAbstractionLayer\\Write\\EntityWriter",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/shopware\\/core\\/Framework\\/DataAbstractionLayer\\/Write\\/EntityWriter.php",
            "line": 161,
            "function": "extractDeleteCommands",
            "class": "Shopware\\Core\\Framework\\DataAbstractionLayer\\Write\\EntityWriter",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/shopware\\/core\\/Framework\\/DataAbstractionLayer\\/VersionManager.php",
            "line": 136,
            "function": "delete",
            "class": "Shopware\\Core\\Framework\\DataAbstractionLayer\\Write\\EntityWriter",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/shopware\\/core\\/Framework\\/DataAbstractionLayer\\/EntityRepository.php",
            "line": 216,
            "function": "delete",
            "class": "Shopware\\Core\\Framework\\DataAbstractionLayer\\VersionManager",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/shopware\\/core\\/Framework\\/Api\\/Controller\\/ApiController.php",
            "line": 929,
            "function": "delete",
            "class": "Shopware\\Core\\Framework\\DataAbstractionLayer\\EntityRepository",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/shopware\\/core\\/Framework\\/Context.php",
            "line": 207,
            "function": "Shopware\\Core\\Framework\\Api\\Controller\\{closure}",
            "class": "Shopware\\Core\\Framework\\Api\\Controller\\ApiController",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/shopware\\/core\\/Framework\\/Api\\/Controller\\/ApiController.php",
            "line": 939,
            "function": "scope",
            "class": "Shopware\\Core\\Framework\\Context",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/shopware\\/core\\/Framework\\/Api\\/Controller\\/ApiController.php",
            "line": 555,
            "function": "executeWriteOperation",
            "class": "Shopware\\Core\\Framework\\Api\\Controller\\ApiController",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/symfony\\/http-kernel\\/HttpKernel.php",
            "line": 152,
            "function": "delete",
            "class": "Shopware\\Core\\Framework\\Api\\Controller\\ApiController",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/symfony\\/http-kernel\\/HttpKernel.php",
            "line": 74,
            "function": "handleRaw",
            "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/symfony\\/http-kernel\\/Kernel.php",
            "line": 202,
            "function": "handle",
            "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/symfony\\/http-kernel\\/HttpCache\\/SubRequestHandler.php",
            "line": 86,
            "function": "handle",
            "class": "Symfony\\Component\\HttpKernel\\Kernel",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/symfony\\/http-kernel\\/HttpCache\\/HttpCache.php",
            "line": 479,
            "function": "handle",
            "class": "Symfony\\Component\\HttpKernel\\HttpCache\\SubRequestHandler",
            "type": "::"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/symfony\\/http-kernel\\/HttpCache\\/HttpCache.php",
            "line": 269,
            "function": "forward",
            "class": "Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/symfony\\/http-kernel\\/HttpCache\\/HttpCache.php",
            "line": 285,
            "function": "pass",
            "class": "Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/symfony\\/http-kernel\\/HttpCache\\/HttpCache.php",
            "line": 213,
            "function": "invalidate",
            "class": "Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/shopware\\/core\\/HttpKernel.php",
            "line": 184,
            "function": "handle",
            "class": "Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/vendor\\/shopware\\/core\\/HttpKernel.php",
            "line": 81,
            "function": "doHandle",
            "class": "Shopware\\Core\\HttpKernel",
            "type": "-\\u003E"
          },
          {
            "file": "\\/var\\/www\\/html\\/public\\/index.php",
            "line": 69,
            "function": "handle",
            "class": "Shopware\\Core\\HttpKernel",
            "type": "-\\u003E"
          }
        ],
        "file": "\\/var\\/www\\/html\\/vendor\\/shopware\\/core\\/Framework\\/DataAbstractionLayer\\/Write\\/EntityWriter.php",
        "line": 272
      }
    }
  ]
}

Uncaught PHP Exception Error: "Call to a member function getFlag() on null" at /var/www/html/vendor/shopware/core/Framework/DataAbstractionLayer/Write/EntityWriter.php line 272

![grafik](https://user-images.githubusercontent.com/28510172/165628461-05b48509-54b1-409e-a3ae-33d18fcf08af.png)
![grafik](https://user-images.githubusercontent.com/28510172/165628491-4c0a7163-3fd6-43ce-b51e-03de440b8e63.png)
![grafik](https://user-images.githubusercontent.com/28510172/165628512-08c6b86d-2068-4b6b-9eeb-16c3315d6170.png)
![grafik](https://user-images.githubusercontent.com/28510172/165628538-b505daf4-4322-4c4c-a07f-740a970e2a61.png)

**Comment by keulinho** [comment] 2022-04-28 09:51
Thanks for your detailed bug report :bug: 

We got already similiar reports und we think the issue lies in media files that are used as a cover in an order lineitem.

Can you check that the media elements that are affected are not just used as a cover of the product, but also as the cover of a order lineitem?

**Comment by rubberfashion** [comment] 2022-04-28 10:56
Hi,

thanks for the update. I set cover_id to NULL in all lineitems, but the issue is still there.

**Comment by keulinho** [comment] 2022-04-28 11:14
For reference here is the issue in the issue tracker: https://issues.shopware.com/issues/NEXT-21320

**Comment by rubberfashion** [comment] 2022-04-28 11:30
Thanks a lot. 
I deleted the Constrains (order lineitem, order_delivery_position) and TRUNCATE order lineitem. Now the issues does not occure.
So the root cause could be order lineitem. 
I did an update to 6.4.10.1 before, but it does not help.

**Comment by rubberfashion** [comment] 2022-04-28 11:46
If i delete all orderlineitem for the specific product_id, i can delete the cover image

**Comment by rubberfashion** [comment] 2022-04-28 11:46
So orderlineitem is the root cause.

**Comment by rubberfashion** [comment] 2022-04-28 12:02
It looks like the code is executing the following SQL: 

SELECT LOWER(HEX(`product.orderLineItems`.`id`)) as id FROM `product` `product` LEFT JOIN `order_line_item` `product.orderLineItems` ON `product`.`id` = `product.orderLineItems`.`product_id` WHERE (`product.orderLineItems`.`id` IS NOT NULL) AND (`product`.`version_id` = 0x0FA91CE3E96A4BC2BE4BD9CE752C3425) AND (`product`.`id` IN (0xE44BE4F721F44BE7AA6411373842E587, 0xEC557786FCC944328C96CD3418754D12));

So it looks for orderlineitems for a the specific product_id. 
So in my opinion the error should happen after the query, try changing the orderLine items or whatever

**Comment by keulinho** [comment] 2022-04-28 12:44
I was able to reproduce the error on 6.4.9.0, but could not reproduce it in the next 6.4.11.0 version, so this issue should be fixed with 6.4.11.0.

**Closed as completed** 2022-04-28 12:56 UTC

**Comment by rubberfashion** [comment] 2022-04-28 13:32
Thanks a lot. When 6.4.11.0 will be released?

**Comment by keulinho** [comment] 2022-04-28 14:08
Soon :tm:

**Comment by keulinho** [comment] 2022-04-28 14:10
There is already a 6.4.11.0 branch here on GitHub, that you can check out. That should be pretty much the version that will be released.
