### ISSUE TITLE
Main variant not displayed on filtered product listing

### ISSUE THREAD

**Issue by kardi31** [shopware/platform#1688] opened 2021-03-08 10:46 UTC
**Description**  
When product listing is displayed, the code to display main variant image is applied. However, when user selects any filter, the code is not applied and user does not see the main variant. That causes confusion among users and frustration among admins/clients as suddenly the main variant they selected for the product is not relevant anymore. 

**Possible Solution**  

**Additional context**  
Is there any reason why this feature is disabled for filtered listings @lernhart ? 
Is there any solution to override this behaviour and display the main variant image both with and without any filters?

**Comment by lernhart** [comment] 2021-03-08 14:48
Hey @kardi31 
While it seems to be confusing, this is actually intended behaviour.

When you apply a filter to a product listing and this results in finding a variant article, the variant article overrides any given property of the parent and will be displayed instead. 

As this can be confusing, we added the product-variant-characteristics at all relevant places in v6.3.0.0 to make it clear, which variant is displayed right now:

![image](https://user-images.githubusercontent.com/21331033/110331821-e2106980-801f-11eb-848a-490bd9a15e58.png)

To replace this behaviour is not an easy task, as the filters are applied deeply in the DAL. You would need to get the product's parent product id and fetch this from the DB and replace it with the original. There is no easy and unhacky solution for this.

**Comment by TimWuyts** [comment] 2022-09-26 06:48
Our client has also noticed this issue during content-load & this is indeed rather strange behavior as you would expect to see the same product variants whenever you narrow down a view using the filters. This is also not as expected according to how you configure the products in the administration.

**Comment by MarcelSchmaeing** [comment] 2024-08-20 07:59
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Closed as not planned by MarcelSchmaeing** 2024-08-20 07:59 UTC
