### ISSUE TITLE
Webhook produces massive amount of MessageDecodingFailedException

### ISSUE THREAD

**Issue by htuscher** [shopware/platform#2703] opened 2022-09-24 12:48 UTC
### PHP Version

8.0.23

### Shopware Version

6.4.15.1

### Expected behaviour

No errors

### Actual behaviour

`WebhookEventMessage` can't be decoded and cause a tremendous amount of errors.

Example:

```
Could not decode message using PHP serialization: O:36:"Symfony\Component\Messenger\Envelope":2:{s:44:"Symfony\Component\Messenger\Envelopestamps";a:1:{s:46:"Symfony\Component\Messenger\Stamp\BusNameStamp";a:1:{i:0;O:46:"Symfony\Component\Messenger\Stamp\BusNameStamp":1:{s:55:"Symfony\Component\Messenger\Stamp\BusNameStampbusName";s:22:"messenger.bus.shopware";}}}s:45:"Symfony\Component\Messenger\Envelopemessage";O:59:"Shopware\Core\Framework\Webhook\Message\WebhookEventMessage":9:{s:68:"Shopware\Core\Framework\Webhook\Message\WebhookEventMessagepayload";a:2:{s:4:"data";a:2:{s:7:"payload";a:1:{s:5:"order";a:42:{s:11:"orderNumber";s:6:"H19485";s:10:"currencyId";s:32:"b7d2554b0ce847cd82f3ac9bd1c0dfca";s:14:"currencyFactor";i:1;s:14:"salesChannelId";s:32:"f57cdb3df84141efbd49388c4013c1f2";s:16:"billingAddressId";s:32:"e3dfa59a0bbf4482bc6e80934d38d4bd";s:13:"orderDateTime";s:29:"2022-06-20T15:00:06.690+00:00";s:9:"orderDate";s:29:"2022-06-20T00:00:00.000+00:00";s:5:"price";a:9:{s:8:"netPrice";d:641.79;s:10:"totalPrice";d:763.73;s:15:"calculatedTaxes";a:1:{i:0;a:5:{s:3:"tax";d:121.94;s:7:"taxRate";i:19;s:5:"price";d:641.79;s:10:"extensions";a:0:{}s:8:"apiAlias";s:19:"cart_tax_calculated";}}s:8:"taxRules";a:1:{i:0;a:4:{s:7:"taxRate";i:19;s:10:"percentage";i:100;s:10:"extensions";a:0:{}s:8:"apiAlias";s:13:"cart_tax_rule";}}
```

We have 62k of them tracked in Sentry.

### How to reproduce

Install any app, that uses a webhook. In our case it's Mailchimp.

Default Shopware installation. Message Queue uses `enqueue` table.
MySQL version: 8.0.30

**Comment by shyim** [comment] 2022-09-27 05:28
Hey,

I cannot reproduce that. Can you attach the whole `dead_message` entry?
And from which event is this triggered?

**Comment by MarcelSchmaeing** [comment] 2024-08-20 07:59
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Closed as not planned by MarcelSchmaeing** 2024-08-20 07:59 UTC
