### ISSUE TITLE
Flow builder actions are empty in 6.4.20

### ISSUE THREAD

**Issue by gaxweb** [shopware/platform#3272] opened 2023-03-14 09:47 UTC
### PHP Version

8.1.16

### Shopware Version

6.4.20

### Expected behaviour

The "action" dropdown in the Flow Builder should contain some basic entries like in other versions.

### Actual behaviour

It doesn't work or is completely empty.

### How to reproduce

1. Install current Flex template with `composer create-project shopware/production:dev-flex <project-name>`
2. Edit .env file to set "dev" environment, URL and DB credentials
3. Go through install process with `./bin/console system:install --basic-setup`
4. Log into admin area
5. Go to Flow Builder settings and open any of the existing flows, then try to add a new action

**Comment by gaxweb** [comment] 2023-03-14 10:50
In Chrome's console there's this error:

```
An error was captured in current module: TypeError: Cannot read properties of undefined (reading 'group')
    at s.shouldShowGroupTitle (app.js?16787909318375437:2:6294083)
    at _t.shouldShowGroupTitle.shouldShowGroupTitle (eval at da (vendors-node.js?16787909312408938:2:1972611), <anonymous>:3:1927)
    at s._t (vendors-node.js?16787909312408938:2:1896658)
    at fn (eval at da (vendors-node.js?16787909312408938:2:1972611), <anonymous>:3:1889)
    at i (vendors-node.js?16787909312408938:2:1895744)
    at s._t (vendors-node.js?16787909312408938:2:1896582)
    at eval (eval at da (vendors-node.js?16787909312408938:2:1972611), <anonymous>:3:545)
    at s.kt [as _l] (vendors-node.js?16787909312408938:2:1896151)
    at s.eval (eval at da (vendors-node.js?16787909312408938:2:1972611), <anonymous>:3:503)
    at e._render (vendors-node.js?16787909312408938:2:1915484)
```

In Firefox it says `An error was captured in current module: TypeError: e is undefined`.

**Comment by shyim** [comment] 2023-08-16 11:11
Hey,

I cannot reproduce the problem you describe in the latest version.

**Comment by pfeitim** [comment] 2023-08-16 11:13
@shyim I have the same problem. 

<img width="588" alt="image" src="https://github.com/shopware/production/assets/16204467/12d8d24d-06bd-4c15-b44c-fd5d7d17ae51">
<img width="1192" alt="image" src="https://github.com/shopware/production/assets/16204467/1b7ba860-5322-4a7b-bafc-e12fb823aa43">

**Comment by pfeitim** [comment] 2023-08-16 11:16
<img width="1463" alt="image" src="https://github.com/shopware/platform/assets/16204467/fe8f96d3-7b1e-464e-9995-f1777aeabc53">

<img width="1607" alt="image" src="https://github.com/shopware/platform/assets/16204467/72fa41ed-8971-4328-adc3-39b229c8204f">

**Comment by pfeitim** [comment] 2023-08-16 11:20
@shyim I'm using the latest version 6.5.4.0 - all flow builder triggers are missing, even in the shopware default flows. Everything is empty. If you want to have a look, please contact me on tim.pfeifer@fortdress-group.com

**Comment by shyim** [comment] 2023-08-16 11:25
Then let's close this as duplicate for #3265

**Closed as not planned by shyim** 2023-08-16 11:25 UTC
