### ISSUE TITLE
The message consumer encountered an error while processing queue message `IterateEntityMessage`

### ISSUE THREAD

**Issue by cuonghuynh** [shopware/platform#3508] opened 2024-01-11 09:11 UTC
### PHP Version

8.2.13

### Shopware Version

6.5.7.2

### Expected behaviour

The message consumer works without exception

### Actual behaviour

The message consumer run failed on the message `Shopware\Core\System\UsageData\EntitySync\IterateEntityMessage`
![image](https://github.com/shopware/shopware/assets/3349033/a7ac1e9b-44af-4940-84f8-001ddea2f448)

### How to reproduce

To reproduce the error:

1. Enable data sharing in Settings > System > Data sharing.
2. Disable the Admin worker.
3. Run `bin/console scheduled-task:run-single usage_data.entity_data.collect`
4. Run `bin/console messenger:consume low_priority` to observe the error (see attached image).

**Comment by lbocker** [comment] 2024-01-16 15:46
Hello,
Thank you for bringing the bug to our attention. We have attempted to replicate the issue but were unsuccessful. Please provide additional information to help us understand and resolve the issue. I greatly appreciate your cooperation.

**Comment by fschmtt** [comment] 2024-01-26 07:34
Hey @cuonghuynh, we'd like to understand what's led to this error on your case. As @lbocker said, we followed your steps and tried different things, but weren't able to reproduce this bug.

Can you give us some more context please? Thank you!

**Comment by fschmtt** [comment] 2024-02-02 15:28
The setup you have encountered this issue on, is it a clone of [shopware/shopware](https://github.com/shopware/shopware) or is Shopware installed as a Composer package?

**Comment by fschmtt** [comment] 2024-02-07 10:39
I'm closing this for now, as we cannot reproduce it without any further information.

Feel free to re-open this issue later on.

**Closed as not planned by fschmtt** 2024-02-07 10:39 UTC
