### ISSUE TITLE
blockOrder - Should have two versions - informative and user change required

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2898] opened 2022-12-22 07:50 UTC
### Please describe the feature you would like to see implemented.

Currently blockOrder is only true/false and it blocks the order from being submitted.

This is in general enough. However, sometimes the prices or other things might change upon order submission which requires one to inform the user about that change before the order is created (as it differs from the data shown on the summary page).

This error should be shown to the user and block the order. However, it does not require the user to change anything.

Whereas other errors, like e.g. shipping address blocked, requires the user to change their address and would allow us to disable the order submit button altogether see also https://github.com/shopware/platform/issues/2542

It could maybe be argued that all errors with `blockOrder=true` and an `errorLevel` <= `WARNING` would only be informative, but separating those two block Order states would be better.  The error object could provide a default implementation that is exactly that scenario.

**Comment by AltayAkkus** [comment] 2022-12-22 09:57
If I understand this correctly:
You want to have two types of blocked orders when running a cart validator, a case which informs the user that he has to change something (e.g. address not allowed), and a case which informs that he has does not have to change anything, but his order is still blocked.

Thing is: Your proposal would only change the way the user is informed about the mistake. Problems that require no user interaction, like you stated, should not be a separate blocked order type, they should not be blocked at all.
You gave the example of price changed while ordering, I never encountered this and can't reproduce it right now, but the user still has to reload the cart, or discard it manually, doesn't he? Best way would be to fix these errors automatically, but then they should not be a case of blocked order but just pass.
The error message which is displayed is customizable, so if I would have a error like price change while ordering I could just say "Sorry! A article in your order has been updated. Please refresh this page".

**Comment by AndreasA** [comment] 2022-12-22 10:27
@AltayAkkus 

Take the following example:
- If the user is already on the checkout summary page and is reviewing their order, or left for a short time before finishing the order (e.g. someone rings the door).
- Someone else opens the admin interface and changes the product price.
- The user clicks submit.
- This triggers a cart re-calculation which will update the product price accordingly.
- This should BLOCK the order and inform the user about the change first.
   - Otherwise they might have to pay more than initially shown.
   - if this happens before the user clicks order submit like e.g. in the cart directly, then it is only an information. However, having temporary block on it, would not hurt it.
- However, this does not require any other user interaction, it just requires the user to confirm the changes.

Another option would be to know that the action happens during an order submit and adjust "blockOrder" accordingly.

With automatic price imports etc. this could be even more tricky.

I actually think this could even be a legal requirement - at least for orders that are e.g. paid by invoice.

Other scenarios are e.g. taxes in the us which can change depending on the time if they deem it necessary.

**Comment by AltayAkkus** [comment] 2022-12-22 11:19
What exactly is the problem with blocking the order and setting the message to something like "Sorry the item XY has changed, please check your renewed order summary"

The legal part makes no sense to me, the legal requirement is that the customers see's what he buys for what price afaik.

EDIT: I'm home in 2 hours, we could hop into Slack and discuss it there, I really have a hard time understanding what the problem to your fix is :D

**Comment by AndreasA** [comment] 2022-12-22 11:43
@AltayAkkus It is a feature request btw. 😄 

Your scenario works. However, the "submit" button would be disabled then and the user cannot re-submit the order immediately without reloading the page.

The price thing is also just an example, there are other scenarios like e.g. informing the user about delivery date changes etc. However, in that scenario the user should be able to just re-submit the order.

Though I guess it might currently be possible to do so as https://github.com/shopware/platform/issues/2542 is still open, though that should be changed with that issue, but for custom implementations e.g. using store API this might already be the case.

And in my scenario above, if the order is not blocked, but auto-corrected and accepted - as there is no error on the order or no blocking error - the customer will never see that anything has changed and the order will be created with different prices.

This scenario might actually be a bug though, as that should not happen.

**Comment by AltayAkkus** [comment] 2022-12-22 13:00
>Your scenario works. However, the "submit" button would be disabled then and the user cannot re-submit the order 

immediately without reloading the page.
OOOOHHH okay. That makes sense. 
So there should be a separate feature to say: Hey, this cart is invalid, block it, but the user can retry. 
I will mention this in the PR

**Comment by AndreasA** [comment] 2022-12-22 13:39
@AltayAkkus Yes. exactly. Sorry, that it took me so long to make this understandable  😄 

It can probably also be done by checking for certain error types directly but I think doing it this way makes it more generic. 

This information could then also be provided by the store API and the corresponding headless frontend could also handle it accordingly.

Strictly speaking there should also be a cart validator - if it does not exist already - that informs the user about changes to their order totals, but I can create a separate issue for that?

**Comment by AltayAkkus** [comment] 2022-12-22 14:23
> It can probably also be done by checking for certain error types directly but I think doing it this way makes it more generic.
> 
> This information could then also be provided by the store API and the corresponding headless frontend could also handle it accordingly.

See my proposal at #2542 



> Strictly speaking there should also be a cart validator - if it does not exist already - that informs the user about changes to their order totals, but I can create a separate issue for that?

I guess? :D I'll check, and write back here.

**Comment by MarcelSchmaeing** [comment] 2024-08-20 07:50
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Closed as not planned by MarcelSchmaeing** 2024-08-20 07:50 UTC
