### ISSUE TITLE
salutation needs to be defined for the customer but is no required field

### ISSUE THREAD

**Issue by jonathan-martz** [shopware/platform#3057] opened 2023-05-02 18:32 UTC
### PHP Version

8.1

### Shopware Version

6.4.20.1

### Expected behaviour

When i place the Order via api client the customer field is required.

### Actual behaviour

but when i create the customer via admin panel it isnt.

### How to reproduce

Create a Customer without Salution, try to place a order via api client placeorder.

**Comment by keulinho** [comment] 2023-05-03 06:36
Duplicate of https://issues.shopware.com/issues/NEXT-25264

I'm closing this in favor of the official issue tracker ticket.

**Closed as completed by keulinho** 2023-05-03 06:36 UTC
