### ISSUE TITLE
sw-modal not getting closed

### ISSUE THREAD

**Issue by maunaw** [shopware/platform#2667] opened 2022-08-24 13:32 UTC
### PHP Version

7.4

### Shopware Version

6.4.14.0

### Expected behaviour

Hi, 

I am trying to use sw-modal component to view pop up in administration, I have my custom component created in which I have got following code for modal getting popped up but when I try to click on close button of modal, it does not work. 

There are no error in browser console, I checked with firefox and chrome. 

`<sw-modal
	  class="test__modal"
	  size="200px"
	  title="modal title"
      > Hello this is modal </sw-modal>`
      
 Please let me know if any changes in above.

### Actual behaviour

Once the modal is popped up, I would like to click on close button and modal should be closed.
The modal is not getting closed at all. 

### How to reproduce

Please try to use the code mentioned in any of the twig file of the custom component. 
`<sw-modal
	  class="test__modal"
	  size="200px"
	  title="modal title"
      > Hello this is modal </sw-modal>`

**Comment by runelaenen** [comment] 2022-11-15 09:55
Hi @maunaw 

This is not a bug.

You will have to implement a `@modal-close="closeModal()"` function in your component.

**Comment by maunaw** [comment] 2022-11-15 10:11
Hi @runelaenen , Thank you for response.
I tried implementing the same @modal-close="closeModal()" but somehow it did not work for me. 
Do you have any other suggestion or code snippet with example for the same?
currently, I am using workaround as notification to show the message instead of modal.
Kindly revert if anything. 
Best Regards!

**Comment by runelaenen** [comment] 2022-11-15 15:17
Hi @maunaw 

Can you paste the modal as you are using it right now? It should be very simple.

For example, if your modal uses `v-if="showMyExampleModal"` to toggle it, the action could be simply `@modal-close="showMyExampleModal = false"`. (But it is of course better to put it in a component-method)

**Comment by MarcelSchmaeing** [comment] 2024-08-20 07:58
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Closed as not planned by MarcelSchmaeing** 2024-08-20 07:58 UTC
