### ISSUE TITLE
Undefined index type in theme DatabaseConfigLoader

### ISSUE THREAD

**Issue by rabauss** [shopware/platform#2057] opened 2021-09-07 09:41 UTC
### PHP Version

7.4.16

### Shopware Version

6.4.4.0

### Expected behaviour

With the Update to 6.4.4.0 the command `system:update:finish` should run without errors, even if you have some theme config variables without `type`.

### Actual behaviour

With the Update to 6.4.4.0 the command `system:update:finish` is not running without errors, because you get the following notice `Undefined index: type` in https://github.com/shopware/platform/blob/dd2bf30d0519dcd9416dc269c88edcfd66f92add/src/Storefront/Theme/ConfigLoader/DatabaseConfigLoader.php#L206

Unfortunately there is no type in the database for custom theme config - maybe we initiated something wrong but the `DatabaseConfigLoader` should not complain about a missing `type` index.

### How to reproduce

Add the following config to your custom `custom/plugins/<yourTheme>/src/Resources/theme.json` and save the config once in the back end.

By the way the given label variables are not used with this config, too - so maybe there is really something wrong with our config or with the json loader?

```json
    "config": {
        "blocks": {
            "testBlock": {
                "label": {
                    "de-DE": "Test",
                    "en-GB": "Test"
                }
            }
        },
        "fields": {
            "test": {
                "block": "testBlock",
                "type": "text",
                "editable": true,
                "label": {
                    "de-DE": "Test-Variable",
                    "en-GB": "Test variable"
                }
            }
        }
    }
```

Afterwards you call the `bin/console system:update:finish` command and you should see the notice `Undefined index: type`.

**Comment by rabauss** [comment] 2021-09-10 13:38
A temporary solution for me was to manually update our `config_values` in the table `theme` and add `,\"type\":\"text\"`. I'm not sure if we always need to create a Migration for new config values or if the JSON loader needs to be updated.

**Comment by BlackScorp** [comment] 2021-10-02 17:33
i cannot reproduce the problem. tried all the steps with vanilla installation, have no errors

**Comment by rabauss** [comment] 2021-10-05 08:29
@alberttomasiak reported same problems to me- maybe he can also help to reproduce the problem.
I haven't tested it with a current vanilla installation but it occurred on an existing installation!

**Comment by shyim** [comment] 2021-10-11 14:01
fixed with https://github.com/shopware/platform/commit/6b6d52090f8b6ba2ae9c0c2acdadbcdfda64a0e5

**Closed as completed by shyim** 2021-10-11 14:01 UTC
