### ISSUE TITLE
Foreign Keys are not created for 1:1 associations

### ISSUE THREAD

**Issue by azngeek** [shopware/platform#2315] opened 2022-02-07 11:44 UTC
### PHP Version

PHP 8

### Shopware Version

6.4.7.0

### Expected behaviour

When creating an entity with a 1:1 relation, i would expect the command `dal:create:schema` to create this association. Given this snippet:

`
return new FieldCollection([
    (new IdField('id', 'id'))->addFlags(new PrimaryKey(), new Required()),

    (new LongTextField('comment', 'name'))->addFlags(new Required()),

    (new FkField('order_id', 'orderId', OrderDefinition::class))->addFlags(new Required()),
    new OneToOneAssociationField('order', 'order_id', 'id', OrderDefinition::class, false),

            new CreatedAtField(),
            new UpdatedAtField()
        ]);
`

### Actual behaviour

This will be created instead:

`
CREATE TABLE `order_refund` (
    `id` BINARY(16) NOT NULL,
    `comment` LONGTEXT NOT NULL,
    `order_id` BINARY(16) NOT NULL,
    `created_at` DATETIME(3) NOT NULL,
    `updated_at` DATETIME(3) NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
`

### How to reproduce

Create an entity with a 1:1 relation.

**Comment by azngeek** [comment] 2022-02-07 11:44
This ticket has been created upon this SO-Question: https://stackoverflow.com/questions/70287163/the-command-dalcreateschema-does-not-create-foreign-keys/71005337#71005337

**Comment by flkasper** [comment] 2022-10-23 19:59
Duplicate of #2222

**Closed as completed** 2022-10-24 07:04 UTC
