### ISSUE TITLE
Dynamic product groups manufacturer are no longer displayed in the dynamic product groups after the update 6.6.6.0

### ISSUE THREAD

**Issue by DMX4ALLGmbH** [shopware/platform#4757] opened 2024-09-17 09:28 UTC
*PHP Version:* 8.2   | *Shopware Version:* 6.6.6.0  | *Affected area / extension:* Extension:Shape-Theme 

 ----

*_Expected behaviour:_*

Dynamic product groups manufacturer are no longer displayed in the dynamic product groups after the update 6.6.6.0

*_Actual behaviour:_*

Dynamic product groups manufacturer are no longer displayed in the dynamic product groups after the update 6.6.6.0

*_How to reproduce:_*

Dynamic product groups manufacturer are no longer displayed in the dynamic product groups after the update 6.6.6.0

**Comment by mitelg** [comment] 2024-10-25 06:57
hey @DMX4ALLGmbH 

as this has not assigned internal Jira ticket, I will close this as duplicate of https://github.com/shopware/shopware/issues/5137

**Closed as not planned** 2024-10-25 06:57 UTC
