### ISSUE TITLE
6.6-rc2 : App name with underscore symbol and storefront js can't be build successfully. Theme compilation error 'directory does not exist'

### ISSUE THREAD

**Issue by averet-lea** [shopware/platform#3574] opened 2024-02-19 08:24 UTC
### PHP Version

8.3

### Shopware Version

6.6.0.0-rc2

### Expected behaviour

I have an app with some javascript code that should work on the storefront.
The app has an underscore symbol in it's name (let's say 'TestABC_DEF').
I am trying to compile the storefront part by running `bin/build-storefront.sh`.
I expect a working storefront part of the app/extension.

I'm using dockware/dev:6.6.0.0-rc2 docker image for my tests (if it's important in this situation).

### Actual behaviour

Webpack builds the bundle successfully placing the file ('test-a-b-c--d-e-f.js') not in `/dist/storefront/js` directory (seem's like it was previously like this?) but creating one more directory `/test-a-b-c--d-e-f/`:
`test-a-b-c--d-e-f (webpack 5.89.0) compiled successfully in 908 ms`

But when compiling theme for sales channel I can see the error:
`The "custom/apps/TestABC_DEF/Resources/app/storefront/dist/storefront/js/test-a-b-c_-d-e-f" directory does not exist.`

So in some places it uses '-' and in some it leaves '_'.

I suppose it can be related to these changes:
[Async JavaScript and get rid of the all.js in the Storefront](https://github.com/shopware/shopware/discussions/3310)
Previously (if i remember it correctly) there was just a file inside /js/ directory without any intermediate ones.

Actually trying to manually change the name of the directory leads to Theme compilation.
But here I receive one more problem.
When it copied it to the Theme folder it looked for 'test-a-b-c_-d-e-f' folder with underscore.
But when then trying to load the page and check how it works in browser I again see the absence of file. 
Now it says that can't find the file in the folder without undescore:
`<script type="text/javascript" src=".../js/test-a-b-c--d-e-f/test-a-b-c--d-e-f.js" defer></script>`

Unfortunately, trying to use any combination of directory name and trying to package and upload the extension via Administration - My Extensions - Upload won't lead to success. It won't work.

Maybe I'm not fully understand the whole process and you'll help. 
Probably there can be a recommendation not to use underscore symbol in app/plugin name, but what if I already have such one and want to update it for coming 6.6 release?

### How to reproduce

Create a simple app/plugin with some minimal storefront js script and name it using underscore ('_') symbol.
Try to build storefront part.

I tried to create a simple app and published it here: [repo](https://github.com/averet-lea/TestABC_DEF)

**Comment by tobiasberge** [comment] 2024-03-06 16:35
Hi @averet-lea,

sorry for my late reply. 

Thank you for providing a test app, thats much appreciated. 👍 

We would actually recommend to use `PascalCase`/`UpperCamelCase` for app as well as plugin names. But admittedly it is not that explicitly told in the [app base guide](https://developer.shopware.com/docs/guides/plugins/apps/app-base-guide.html) as it is in the [plugin base guide](https://developer.shopware.com/docs/guides/plugins/plugins/plugin-base-guide.html#name-your-plugin) at the moment. In the app docs all examples are PascalCase wheras the plugin docs additionally state "written in UpperCamelCase".

https://developer.shopware.com/docs/guides/plugins/plugins/plugin-base-guide.html#name-your-plugin

The new sub-folder inside `dist/storefront/js/your-app-technical-name/` is expected in 6.6 and will be copied later into `/public/theme`. This is needed so webpack knows from which folder async JS files are supposed to be loaed. Each app has its own folder for separation and to prevent naming conflicts. With the async JS possibility there can now be more generated JS dist files in an app/plugin. Previously everything was merged into the all.js in 6.5.

Your example repo was supposed to be used as an app, right? Because it also has a composer.json but no plugin class so I was not 100% sure. But installing as app worked out fine.

I was not able to reproduce the issue `The "custom/apps/TestABC_DEF/Resources/app/storefront/dist/storefront/js/test-a-b-c_-d-e-f" directory does not exist.`

* Installed and activated as an app
* Run `composer build:js:storefront` (Also runs `theme:compile`)
* Compiled as expected with output:

```
# Plugin "TestABC_DEF": Injected successfully

 ✔ Shopware 6 Storefront
   Compiled successfully in 1.32s

 ✔ TestABC_DEF


shopware-6-storefront:
  78 assets
  617 modules
  shopware-6-storefront (webpack 5.89.0) compiled successfully in 1339 ms

test-a-b-c--d-e-f:
  1 asset
  10 modules
  test-a-b-c--d-e-f (webpack 5.89.0) compiled successfully in 349 ms
> cd src/Storefront/Resources/app/storefront && node copy-to-vendor.js
- copied "/Users/tobiasberge/www/platform/src/Storefront/Resources/app/storefront/node_modules/tiny-slider" to "/Users/tobiasberge/www/platform/src/Storefront/Resources/app/storefront/vendor/tiny-slider"
- copied "/Users/tobiasberge/www/platform/src/Storefront/Resources/app/storefront/node_modules/bootstrap" to "/Users/tobiasberge/www/platform/src/Storefront/Resources/app/storefront/vendor/bootstrap"
- copied "/Users/tobiasberge/www/platform/src/Storefront/Resources/app/storefront/node_modules/flatpickr" to "/Users/tobiasberge/www/platform/src/Storefront/Resources/app/storefront/vendor/flatpickr"

✓ Done, all directories / files copied successfully.
Execution time: 167.880917ms
> @php bin/console theme:compile
Start theme compilation

 Compiling theme for sales channel for : 018e13c4f03670739042fc11ef720fcb

 ! [NOTE] Took 1.931193 seconds
```

I can also see the `console.log` with `init` as well as the apps `<script>` tag.

![image](https://github.com/shopware/shopware/assets/8480203/85c58ce3-d733-47fc-bcf6-58a67311f014)

![image](https://github.com/shopware/shopware/assets/8480203/9581bde5-7d81-4fd4-b042-bb564601f35a)

Maybe you can try again with the latest rc-4 or `trunk` since it was tested with rc-2.

And you always have the option to rename everything to `PascalCase` then you are on the safe side. This works the same in 6.5 and 6.6.

**Comment by averet-lea** [comment] 2024-03-10 12:01
Hello @tobiasberge,
Thank you very much for your detailed answer!
Sorry for replying only now (missed the notification).

I've just tried it with rc-4 (using `bin/build-storefront.sh`) and now it works correctly. 
So maybe something was wrong with rc-2, rc-3.

It's definitely a good idea about renaming to `PascalCase`, but what if we already have an app registered in Shopware Store and it's technical name has underscore in it's name (the hint there says that _'the technical name is unique and can't be changed afterwards'_)? I suppose it will be hard to change the name there:) 
But certainly for new extensions we should follow `PascalCase`.

So, as a conclusion: no more bug in 6.6.0.0-rc-4.
Of course, it would be nice to know what the cause was, but at least everything works now.

Should I close the issue, or will you do it with some comment from your side (or some further investigation if required)?

**Comment by tobiasberge** [comment] 2024-03-11 09:24
Hi @averet-lea,

thank you for testing and for your feedback. 👍 I would say if you already have an app with this naming and everything works for you at the moment, it is fine to keep it this way. I can totally understand that it can be a headache to change it afterwards. But for future Apps/Plugins I would stick with PascalCase.

We also adjusted the app docs now to make it more clear.

If the issue is resolved for you, you can already close it. In the meantime we will check what change fixed it and post another comment.

**Closed as completed** 2024-03-11 09:45 UTC
